export function createInitialState() {
  return {
    frames: [],
    frameCanvases: [],
    frameHashes: [],
    enabled: [],
    width: 0,
    height: 0,
    fps: 12,
    loopMode: 'loop',
    playing: false,
    currentFrame: 0,
    onionSkin: false,
    bgMode: 'transparent',
    bgColor: '#336699',
    animTimer: null,
    pingPongReverse: false,
    sheetCols: 8,
    exportScale: 1,
    exportFormat: 'png',
    atlasFormat: 'texturepacker_hash',
    trimAlphaBounds: true,
    trimPadding: 1,
    startFrame: 0,
    endFrame: 0,
    skipFrames: 0,
    keyEnabled: false,
    keyColor: [255, 255, 255],
    keyTolerance: 40,
    keySoftness: 20,
    keyDespill: 50,
    eyedropperActive: false,
    loopDetection: null,
  };
}
